name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"
    - name: Build SwiftDemo
      run: |
        xcodebuild clean build \
          -project DeviceIDDemo.xcodeproj \
          -scheme SwiftDemo \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16'
    - name: Build ObjCDemo
      run: |
        xcodebuild clean build \
          -project DeviceIDDemo.xcodeproj \
          -scheme ObjCDemo \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16'
